name: Daily Social Media Bot

on:
  schedule:
   # - cron: '*/5 * * * *' # runs every 5 mins
    - cron: '30 10 * * *'  # Runs every day at 4:00 PM IST
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      IG_USERNAME: ${{ secrets.IG_USERNAME }}
      IG_PASSWORD: ${{ secrets.IG_PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot script
      run: python posts-bot.py
